---
title: "Repeated-Measures / Within-Subjects ANOVA in R"
format: html
editor: visual
embed-resources: true
---

## **One-way repeated measures ANOVA test**

<https://www.statskingdom.com/repeated-anova-calculator.html>

<https://www.geeksforgeeks.org/repeated-measures-within-subjects-anova-in-r/>

We will use a simulated dataset to explain how to perform a Repeated-Measures ANOVA. In this example, we'll assume we have a dataset where subjects are measured at three different time points.

```{r}
library(tidyverse)
```

### Step 1: Simulate Data

```{r}
# Set seed for reproducibility
set.seed(123)

# Simulate data for 10 subjects measured at 3 time points
subject <- factor(rep(1:10, each = 3))
time <- factor(rep(c("T1", "T2", "T3"), times = 10))
response <- c(
  rnorm(10, mean = 50, sd = 5), # T1
  rnorm(10, mean = 55, sd = 5), # T2
  rnorm(10, mean = 60, sd = 5)  # T3
)

# Create a data frame
data <- data.frame(subject, time, response)
```

### Step 2: Fit the Repeated-Measures ANOVA Model

```{r}
# Perform Repeated-Measures ANOVA
aov_model <- aov(response ~ time + Error(subject/time), data = data)

# View the summary of the ANOVA
summary(aov_model)


aov_model1 <- aov(response ~ time + Error(subject), data = data)

# View the summary of the ANOVA
summary(aov_model1)
```

```{r}
lmer_model <- lme4::lmer(response~ time+(1|subject), REML = FALSE)
summary(lmer_model)


```

```{r}
data %>% group_by(time) %>% summarise(mean(response))

data %>% summarise(mean(response))

# overall sum of square 
ss_tot <- var(data$response)*(30-1)

# sum of square for between time
ss_time <- 10*((55.36234-54.76448)^2+
    (53.07152	-54.76448)^2+
    (55.85958 -54.76448)^2
)

# sum of square for within subject
d1 <- data %>% group_by(subject) %>% summarise(subjmean=mean(response)) %>% bind_cols(
  data %>% pivot_wider(names_from = time, values_from = response) %>% 
  select(-subject) ) %>% 
  mutate(dev1=((T1-subjmean)^2+(T2-subjmean)^2+(T3-subjmean)^2),
         overallmean=mean(subjmean),
         dev2=(subjmean-overallmean)^2)

ss_sub_wthin <- d1 %>% summarise(sum(dev1))

# sum of square for between subject
ss_sub_between <- d1 %>% summarise(sum(dev2))
  


c(ss_tot, ss_time, ss_sub_wthin, ss_sub_between)
#611.937+112.0754+44.22794-948.1631

data %>% pivot_wider(names_from = time, values_from = response) %>% 
  select(-subject) %>% ggplot() + 
  geom_point(aes(x=T1, y=T2), color="red") +   
  stat_cor(aes(x=T1, y=T2), p.accuracy = 0.001, r.accuracy = 0.01, color="red")  + 
  geom_point(aes(x=T1, y=T3), color="blue") +
  stat_cor(aes(x=T1, y=T3), p.accuracy = 0.001, r.accuracy = 0.01, 
           color="blue", label.x.npc="center")
```
